enable-module-update = true # set this to false if you do not want to receive updates for the module
parallel-jobs = 1

patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "both"                                                   
app-name = "YT"
excluded-patches = "'Enable debugging'"                                
included-patches = ""                                                 
patcher-args = "-OdarkThemeBackgroundColor=#FF000000"
version = "auto"                                                   
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
module-prop-name = "yt-rv"

[Music]
build-mode = "both"
app-name = "YT-Music"
excluded-patches = ""
included-patches = "'Compact header'"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
module-prop-name = "ytm-rv"
arch = "both"

[Reddit]
app-name = "Reddit RVC"
rv-brand = "RVC"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
dpi = "120-640dpi"

[Twitter]
app-name = "Twitter Piko"
patches-source = "crimera/piko"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Piko"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"
build-mode = "both"
include-stock = "split"

[Twitch]
app-name = "Twitch RVC"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch/"
uptodown-dlurl = "https://twitch.en.uptodown.com/android"
